### PR TITLE
fix error in example with dictionaries in ch24

### PR DESCRIPTION
**Pull request by victorhck**
I think that is an error, right?
BTW, I find this section of dictionaries a bit confussing...
At the beginnig of the section, what are the items in a dictionarie, why are shown in that way, etc... (IMHO)

PS: I almost reach the end of the chapter!!

### CODE REVIEW

**Comment by iggredible** [comment]
The examples are actually correct :)
Just run these commands:
```
:let mealPlans = #{breakfast: "waffles", lunch: "pancakes", dinner: "donuts"}
:call map(mealPlans, 'v:key . " and milk"')

:echo mealPlans
" returns {'lunch': 'lunch and milk', 'breakfast': 'breakfast and milk', 'dinner': 'dinner and milk'}
```

I think I see where your confusion was. You're expecting the dictionary to map the values. But in this case, we are mapping the keys (note the `v:key` in `call map(mealPlans, 'v:key . " and milk"')`). The keys in `mealPlans` are `breakfast lunch dinner`.

**Comment by iggredible** [comment]
Thanks for the input! I will re-read them again when I get a chance :) I really appreciate your translation efforts and the PRs.

**Comment by iggredible** [comment]
I'm going to keep this PR open until I'm done re-reading Ch 24.

**Comment by victorhck** [comment]
Ok, sorry for the noise, now I can see how the command works...

**Comment by iggredible** [comment]
@victorhck you're right, it could be clearer. I updated Ch 24 Dictionary Functions section. I added an example using `v:val` in addition to `v:key` to give more clarity :).

**Comment by victorhck** [comment]
it's more clear now! thanks a lot.
BTW, there is just a question, if you have:

```
:let mealPlans = #{breakfast: "waffles", lunch: "pancakes", dinner: "donuts"}
:call map(mealPlans, 'v:val . " and milk"')
```
Why if you run
```
:echo mealPlans
" returns {'lunch': 'pancakes and milk', 'breakfast': 'waffles and milk', 'dinner': 'donuts and milk'}
```
The dictionary it's not show in same order? I mean, why not, first breakfast, then lunch, and later dinner. In the same order I set in let command?

Thanks a lot for your work!!

**Pull request closed without merging**
