### PR TITLE
Add file type in code samples

### PR DESCRIPTION
**Pull request by joaothallis**

### CODE REVIEW

**Comment by iggredible** [comment]
@joaothallis I tried this approach before but I decided against it because VimScript is not a widely supported language in Markdown To keep it consistent, I decided to not add _any_ file type in the code examples.

**Comment by joaothallis** [comment]
> @joaothallis I tried this approach before but I decided against it because VimScript is not a widely supported language in Markdown To keep it consistent, I decided to not add _any_ file type in the code examples.

@iggredible I see this blog post https://www.rubycoloredglasses.com/2013/04/languages-supported-by-github-flavored-markdown/ that says that GitHub uses Linguist and Linguist supports Vim Script https://github.com/github/linguist/blob/0cc037b85b488f1ae1ad7055aeee42a9dfc3cf26/lib/linguist/languages.yml#L5938

I do a commit to test this: https://github.com/iggredible/Learn-Vim/pull/49/commits/363ab0c2161e2264cd56aba13366c4273da2f9ed

**Comment by iggredible** [comment]
Sounds good. It looks like you still have this PR in Draft (Can't merge it). 
When you are finished, let me know; I will review and merge it if it looks good. Thanks.

**Comment by iggredible** [comment]
I merged it. It works! If you want to update the rest of the ch, feel free. Otherwise, I'll update it when I am done with all the chapters.

**Comment by joaothallis** [comment]
@iggredible I will update the rest, I will enjoy reading :)

**Pull request merged**
