### PR TITLE
Changing the Hyperlink to my repository,

### PR DESCRIPTION
**Pull request by EliazBobadilla**
I highly recommend that you put my repository since I have already finished translating everything up to the current date while that repository only goes up to chapter 15.
I am very active so as soon as you make an update I could translate it and put it in my repository.

### CODE REVIEW

**Comment by EliazBobadilla** [comment]
If you want me to make a change to my repository just let me know and I will do it as soon I can.

**Comment by iggredible** [comment]
Hi @EliazBobadilla, I think for the best interest of both you and the other translator, we should include the repository for both, and let the users decide which translation to use.

Can you add yours below the current Spanish translation?

**Comment by EliazBobadilla** [comment]
It's okay.

**Comment by EliazBobadilla** [comment]
Ready. Thank you for responding quickly!

**Comment by iggredible** [comment]
Looks good. Thanks!

**Pull request merged**
