### PR TITLE
capital letter for commands ch11

### PR DESCRIPTION
**Pull request by victorhck**

### CODE REVIEW

**Comment by iggredible** [comment]
Good catch! You're really good at catching these small things :)

**Comment by victorhck** [comment]
I'm doing a whole review in my translation, and I :vsp with your guide, so update the text and at same time catch some typos in your text.

BTW: In that chapter, [you say](https://github.com/iggredible/Learn-Vim/blob/master/ch11_visual_mode.md#incrementing-numbers) that with `Ctrl-A` I can increment numbers under a block wise selection in visual mode. I follow the guide:

* Start block-wise visual mode and go down 3 lines (Ctrl-V 3j). This highlights the remaining "1"s. Now all "1" should be highlighted (except the first line).
* Run g Ctrl-A.

And nothing happens, I have to run Ctrl-A again to get the work done. Maybe I'm doing something wrong??

**Comment by iggredible** [comment]
Weird. That trick should work. Check out `:h v_g_CTRL-A` in your Vim.

**Comment by victorhck** [comment]
I tried in a Vim without plugins or configurations and works well... Maybe something in my config is _broken_ that...
Anyway, thanks!

**Comment by iggredible** [comment]
Yup, no problem! :D

**Pull request merged**
